create SCHEMA IF NOT EXISTS securecapita;
--SET NAMES 'UTF9MB4';
--SET TIME_ZONE = 'US/Eastern';
--SET TIME_ZONE = '-4';

use securecapita;

DROP TABLE IF EXISTS Users;

create TABLE Users
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    title VARCHAR(30) DEFAULT NULL,
    bio VARCHAR(255) DEFAULT NULL,
    enabled BOOLEAN DEFAULT FALSE,
    non_locked BOOLEAN DEFAULT TRUE,
    using_mfa BOOLEAN DEFAULT FALSE,
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    image_url VARCHAR(255) DEFAULT 'https://toppng.com/public/uploads/preview/user-account-management-logo-user-icon-11562867145a56rus2zwu.png',
    CONSTRAINT UQ_USERS_EMAIL_CONSTRAINT UNIQUE (email)
);


DROP TABLE IF EXISTS Roles;

create TABLE Roles
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    permission VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_ROLES_NAME_CONSTRAINT UNIQUE (name)
);

DROP TABLE IF EXISTS UserRoles;

create TABLE UserRoles
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL ,
    role_id BIGINT UNSIGNED NOT NULL ,
    FOREIGN KEY (user_id) REFERENCES UserS(id) ON delete CASCADE ON update CASCADE,
    FOREIGN KEY (role_id) REFERENCES UserS(id) ON delete RESTRICT ON update CASCADE,
    CONSTRAINT UQ_USERROLES_USER_ID_CONSTRAINT UNIQUE (user_id)
);

DROP TABLE IF EXISTS Events;

create TABLE Events
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_EVENTS_TYPE_CONSTRAINT UNIQUE (type)
);

DROP TABLE IF EXISTS UserEvents;

create TABLE UserEvents
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL ,
    event_id BIGINT UNSIGNED NOT NULL ,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON delete CASCADE ON update CASCADE,
    FOREIGN KEY (event_id) REFERENCES Events(id) ON delete RESTRICT ON update CASCADE
);